# Generated by Django 2.0.5 on 2018-05-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
